const searchQueryMOck = {
    "site_id": "MLB",
    "country_default_time_zone": "GMT-03:00",
    "query": "carro",
    "paging": {},
    "results": [
      {
        "id": "MLB3539492769",
        "title": "Volkswagen Fox 1.6 Msi Highline 16v 2016",
        "condition": "used",
        "thumbnail_id": "600181-MLB73302303148_122023",
        "catalog_product_id": "MLB7423803",
        "listing_type_id": "gold_premium",
        "permalink": "https://carro.mercadolivre.com.br/MLB-3539492769-volkswagen-fox-16-msi-highline-16v-2016-_JM",
        "buying_mode": "classified",
        "site_id": "MLB",
        "category_id": "MLB1744",
        "domain_id": "MLB-CARS_AND_VANS",
        "thumbnail": "http://http2.mlstatic.com/D_600181-MLB73302303148_122023-I.jpg",
        "currency_id": "BRL",
        "order_backend": 1,
        "price": 52900,
        "original_price": null,
        "sale_price": null,
        "available_quantity": 1,
        "official_store_id": null,
        "use_thumbnail_id": true,
        "accepts_mercadopago": false,
        "shipping": {
          "store_pick_up": false,
          "free_shipping": false,
          "logistic_type": null,
          "mode": "not_specified",
          "tags": [
          ],
          "benefits": null,
          "promise": null
        },
        "stop_time": "2024-04-10T04:00:00.000Z",
        "seller": {
          "id": 520709672,
          "nickname": "VITORIA.VEÍCULOS"
        },
        "attributes": [
          {
            "id": "ITEM_CONDITION",
            "name": "Condição do item",
            "value_id": "2230581",
            "value_name": "Usado",
            "attribute_group_id": "",
            "attribute_group_name": "",
            "value_struct": null,
            "values": [],
            "source": 1,
            "value_type": "list"
          },
          {
            "id": "ENGINE",
            "name": "Motor",
            "value_id": "2164443",
            "value_name": "1.6",
            "attribute_group_id": "ADICIONALES",
            "attribute_group_name": "Adicionais",
            "value_struct": null,
            "values": [],
            "source": 3145348869647973,
            "value_type": "string"
          },
          {
            "id": "SINGLE_OWNER",
            "name": "Único dono",
            "value_id": "242084",
            "value_name": "Não",
            "attribute_group_id": "ADICIONALES",
            "attribute_group_name": "Adicionais",
            "value_struct": null,
            "values": [],
            "source": 3145348869647973,
            "value_type": "boolean"
          },
          {
            "id": "TRANSMISSION",
            "name": "Transmissão",
            "value_id": "370877",
            "value_name": "Manual",
            "attribute_group_id": "ADICIONALES",
            "attribute_group_name": "Adicionais",
            "value_struct": null,
            "values": [],
            "source": 3145348869647973,
            "value_type": "list"
          },
          {
            "id": "HAS_AIR_CONDITIONING",
            "name": "Ar-condicionado",
            "value_id": "242085",
            "value_name": "Sim",
            "attribute_group_id": "CONFORT",
            "attribute_group_name": "Conforto",
            "value_struct": null,
            "values": [],
            "source": 3145348869647973,
            "value_type": "boolean"
          },
          {
            "id": "ENGINE_DISPLACEMENT",
            "name": "Cilindrada",
            "value_id": "2326646",
            "value_name": "1.6 L",
            "attribute_group_id": "DFLT",
            "attribute_group_name": "Outros",
            "value_struct": {},
            "values": [],
            "source": 3298252595505050,
            "value_type": "number_unit"
          },
          {
            "id": "LENGTH",
            "name": "Comprimento",
            "value_id": "490486",
            "value_name": "3868 mm",
            "attribute_group_id": "DFLT",
            "attribute_group_name": "Outros",
            "value_struct": {},
            "values": [],
            "source": 3298252595505050,
            "value_type": "number_unit"
          },
          {
            "id": "PASSENGER_CAPACITY",
            "name": "Quantidade de pessoas",
            "value_id": "458562",
            "value_name": "5",
            "attribute_group_id": "DFLT",
            "attribute_group_name": "Outros",
            "value_struct": null,
            "values": [],
            "source": 3298252595505050,
            "value_type": "number"
          },
          {
            "id": "POWER",
            "name": "Potência",
            "value_id": "458735",
            "value_name": "110 hp",
            "attribute_group_id": "DFLT",
            "attribute_group_name": "Outros",
            "value_struct": {},
            "values": [],
            "source": 3298252595505050,
            "value_type": "number_unit"
          },
          {
            "id": "BRAND",
            "name": "Marca",
            "value_id": "60249",
            "value_name": "Volkswagen",
            "attribute_group_id": "FIND",
            "attribute_group_name": "Ficha técnica",
            "value_struct": null,
            "values": [],
            "source": 3145348869647973,
            "value_type": "string"
          },
          {
            "id": "DOORS",
            "name": "Portas",
            "value_id": null,
            "value_name": "4",
            "attribute_group_id": "FIND",
            "attribute_group_name": "Ficha técnica",
            "value_struct": null,
            "values": [],
            "source": 3145348869647973,
            "value_type": "number"
          },
          {
            "id": "FUEL_TYPE",
            "name": "Tipo de combustível",
            "value_id": "372591",
            "value_name": "Gasolina e álcool",
            "attribute_group_id": "FIND",
            "attribute_group_name": "Ficha técnica",
            "value_struct": null,
            "values": [],
            "source": 3145348869647973,
            "value_type": "list"
          },
          {
            "id": "KILOMETERS",
            "name": "Quilômetros",
            "value_id": null,
            "value_name": "108585 km",
            "attribute_group_id": "FIND",
            "attribute_group_name": "Ficha técnica",
            "value_struct": {},
            "values": [],
            "source": 3145348869647973,
            "value_type": "number_unit"
          },
          {
            "id": "MODEL",
            "name": "Modelo",
            "value_id": "36763",
            "value_name": "Fox",
            "attribute_group_id": "FIND",
            "attribute_group_name": "Ficha técnica",
            "value_struct": null,
            "values": [],
            "source": 3145348869647973,
            "value_type": "string"
          },
          {
            "id": "TRIM",
            "name": "Versão",
            "value_id": null,
            "value_name": "1.6 MSI HIGHLINE 16V",
            "attribute_group_id": "FIND",
            "attribute_group_name": "Ficha técnica",
            "value_struct": null,
            "values": [],
            "source": 3145348869647973,
            "value_type": "string"
          },
          {
            "id": "VEHICLE_YEAR",
            "name": "Ano",
            "value_id": "423562",
            "value_name": "2016",
            "attribute_group_id": "FIND",
            "attribute_group_name": "Ficha técnica",
            "value_struct": null,
            "values": [],
            "source": 3145348869647973,
            "value_type": "number"
          },
          {
            "id": "FIPE_BRAND",
            "name": "Marca FIPE",
            "value_id": "8072700",
            "value_name": "vw - volkswagen",
            "attribute_group_id": "OTHERS",
            "attribute_group_name": "Outros",
            "value_struct": null,
            "values": [],
            "source": 3298252595505050,
            "value_type": "string"
          },
          {
            "id": "FIPE_MODEL",
            "name": "Modelo FIPE",
            "value_id": "8593514",
            "value_name": "fox highline1.6 flex 16v 5p",
            "attribute_group_id": "OTHERS",
            "attribute_group_name": "Outros",
            "value_struct": null,
            "values": [],
            "source": 3298252595505050,
            "value_type": "string"
          },
          {
            "id": "VERIFIED_VEHICLES",
            "name": "Veículos verificados",
            "value_id": "242085",
            "value_name": "Sim",
            "attribute_group_id": "OTHERS",
            "attribute_group_name": "Outros",
            "value_struct": null,
            "values": [],
            "source": 3298252595505050,
            "value_type": "boolean"
          },
          {
            "id": "TRACTION_CONTROL",
            "name": "Controle de tração",
            "value_id": "493979",
            "value_name": "Dianteira",
            "attribute_group_id": "SECURITY",
            "attribute_group_name": "Segurança",
            "value_struct": null,
            "values": [],
            "source": 3298252595505050,
            "value_type": "list"
          }
        ],
        "location": {
          "address_line": "",
          "zip_code": "",
          "subneighborhood": null,
          "neighborhood": {},
          "city": {},
          "state": {},
          "country": {}
        },
        "seller_contact": {},
        "installments": null,
        "winner_item_id": null,
        "catalog_listing": false,
        "discounts": null,
        "promotions": [
        ],
        "inventory_id": null
      },
      {
        "id": "MLB3429984079",
        "title": "Ford Ka + 1.0 Tivct Se Plus",
        "condition": "used",
        "thumbnail_id": "691755-MLA71972599988_092023",
        "catalog_product_id": "MLB8011409",
        "listing_type_id": "gold_premium",
        "permalink": "https://carro.mercadolivre.com.br/MLB-3429984079-ford-ka-10-tivct-se-plus-_JM",
        "buying_mode": "classified",
        "site_id": "MLB",
        "category_id": "MLB1744",
        "domain_id": "MLB-CARS_AND_VANS",
        "thumbnail": "http://http2.mlstatic.com/D_691755-MLA71972599988_092023-I.jpg",
        "currency_id": "BRL",
        "order_backend": 2,
        "price": 49900,
        "original_price": null,
        "sale_price": null,
        "available_quantity": 1,
        "official_store_id": null,
        "use_thumbnail_id": true,
        "accepts_mercadopago": false,
        "shipping": {},
        "stop_time": "2024-04-16T04:00:00.000Z",
        "seller": {},
        "attributes": [],
        "location": {},
        "seller_contact": {},
        "installments": null,
        "winner_item_id": null,
        "catalog_listing": false,
        "discounts": null,
        "promotions": [
        ],
        "inventory_id": null
      },
    ]
}

export default searchQueryMOck;